# Generated by Django 5.2.1 on 2025-06-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_block_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
